## Outline
1. PyTorch
2. What are tensors
3. Initialising, slicing, reshaping tensors
4. Numpy and PyTorch interfacing
5. GPU support for PyTorch + Enabling GPUs on Google Colab
6. Speed comparisons, NumPy - PyTorch - PyTorch on GPU
7. Autograd concepts and application
8. Writing basic learning loop using autograd
9. Exercises

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

All operations very similar to NumPy

# Initialise tensors

Initialise using in-built functions

In [3]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.9766, 0.0918],
        [0.1453, 0.3810],
        [0.4336, 0.8751]])


In [7]:
x = torch.empty(3,2)
# Creates space but doesn't initialise values in it. So just has the values which were there initially in memory (could be NaN too)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[2.1517e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
x = torch.linspace(0,1, steps = 5)
# Include 0 and 1
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


Initialising manually

In [10]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


# Slicing tensors

In [11]:
print(x.size()) # like x.shape in numpy
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [13]:
y = x[1,1]
print(y) # y is still of type tensor
print(y.item()) # To get numerical/scalar value of a tensor

tensor(4)
4


# Reshaping tensors

In [14]:
print(x)
y = x.view(2,3) # Similar to numpy.reshape()
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
y = x.view(6, -1) # when we want particularly one dimension as we want (6) and it can fix the other dimension suitably to fit all items itself (-1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


Mismatch in tensor dimensions biggest bug in tensor-world/DL. And knowing what each axis means (input/batch/weight)

# Simple Tensor Operations

In [16]:
# Pointwirse Operations
x = torch.ones([3,2])
y = torch.ones([3,2])
z = x + y
print(z)
z = x-y
print(z)
z = x*y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [17]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [19]:
z = y.add_(x) # Modifies y too (_ => modify-in-place). Adds x to y. z modified as well
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


Useful if don't want to generate new tensors everytime